In [1]:
import numpy as np
import pandas as pd
#importing dataframe, new variables and prepare for training
file=1
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [2]:
#apply tags according to map
gps['action']='road'
gps['action'].loc[gps['zmax']>-0.2]='using_phone'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[(gps['speed']<2)&(gps['zmax']>-0.2)]='low_speed,using_phone'
gps['action'].loc[gps['speed']==0]='stopped'

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [3]:
#save as dataframe gps1
gps1=gps

In [4]:
#now let us do second file
file=2
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [6]:
#apply tags 
gps['action']='road'
gps['action'].loc[gps['zmin']<-0.5]='using_phone'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[(gps['speed']<2)&(gps['zmin']<-0.5)]='low_speed,using_phone'
gps['action'].loc[gps['speed']==0]='stopped'
gps2=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [7]:
#Third file
file=3
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [9]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['zmin']<-2]='bump'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps.index>11713]='stopped, phone_at_rest'
gps3=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [10]:
#fourth set

#now let us do second file
file=4
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [12]:
#apply tags
gps['action']='road'
gps['action'].loc[gps['zmin']<-2.2]='bump'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[(gps['speed']<2)&(gps['ymax']>1)]='low_speed,using_phone'
gps['action'].loc[gps['speed']==0]='stopped'
gps4=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [13]:
#fifth file

#now let us do second file
file=5
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:57: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [14]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['ymax']>4]='impact, dropped_phone'
gps['action'].loc[(gps['speed']<2)&(gps['speed']>1)]='crossing_speed'
gps['action'].loc[(gps['speed']>0.5)&(gps['speed']<2)&(gps['ymax']>1)]='low_speed,using_phone'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['ymin']<-2]='bump'
gps['action'].loc[gps['xmax']>3]='bump'


/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [15]:
gps['action'].loc[gps['ymax']>4]='impact, dropped_phone'
gps['action'].loc[gps.index>6715]='stopped, phone_at_rest'
gps5=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [16]:
#file number 6

file=6
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [17]:
#apply tags 
gps['action']='road'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['zmin']<-2.5]='bump'
gps['action'].loc[gps['zmax']>3]='bump'

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [18]:
gps['action'].loc[(gps['zdiff']<0.007)&(gps['speed']==0)]='stopped, phone_at_rest'
gps6=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [19]:
#seventh file
file=7
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [20]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['zmin']<-2.5]='bump'
gps['action'].loc[gps['zmax']>3]='bump'
gps7=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [21]:
#eighth file

file=8
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [22]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['xmax']>4]='accident'
gps['action'].loc[gps.index>4848]='stopped, phone_at_rest'
gps8=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [23]:
#9th

file=9
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [24]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['ymax']>3]='bump'
gps['action'].loc[gps.index>4167]='stopped, phone_at_rest'
gps9=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [25]:
#10th file

file=10
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:56: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [26]:
#apply tags to everything
gps['action']='road'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['ymin']<-4]='impact, dropped_phone'
gps['action'].loc[gps.index>7772]='low_speed,using_phone'
gps['action'].loc[gps.index>10078]='stopped, phone_at_rest'
gps10=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [27]:
#13 is interesting
file=13
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [28]:
gps['action']='road'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[(gps['speed']>0.5)&(gps['speed']<2)&(gps['ymax']>1.5)]='low_speed,using_phone'
gps['action'].loc[gps['speed']==0]='stopped'
gps13=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [29]:
#14th which is another accident
file=14
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [30]:
gps['action']='road'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['xmax']>4]='accident'
gps['action'].loc[gps.index>2133]='stopped, phone_at_rest'
gps14=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [31]:
#end the training with file 21. Walking to the airport
file=21
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:54: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:55: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [32]:
gps['action']='road'
gps['action'].loc[gps['speed']<2]='crossing_speed'
gps['action'].loc[gps['speed']==0]='stopped'
gps['action'].loc[gps['ymin']<-2]='low_speed,using_phone'
gps21=gps

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [33]:
#creating a single dataframe for training
frames=[gps1,gps2,gps3,gps4,gps5,gps6,gps7,gps8,gps9,gps10,gps13,gps14,gps21]
gps=pd.concat(frames)

In [35]:
#dropping timelapse which we don't need
gps.drop('timelapse',axis=1,inplace=True)

In [37]:
#prediction time, we test a variety of models to check accuracy
import pandas
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [38]:
#train the model with 20% of data ledt for validation
array = gps.values
X = array[:,2:13]
Y = array[:,13]
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [39]:
#so, split in 10 parts and train in 9, test in 1
seed = 7
scoring = 'accuracy'

In [40]:
#time to train and check algorithm suitability
models = []
models.append(('LR', LogisticRegression()))
models.append(('LDA', LinearDiscriminantAnalysis()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('CART', DecisionTreeClassifier()))
models.append(('NB', GaussianNB()))
models.append(('SVM', SVC()))
# evaluate each model in turn
results = []
names = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=seed)
    cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

LR: 0.854133 (0.007282)


/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:388: UserWarn

LDA: 0.780042 (0.008287)
KNN: 0.956820 (0.003978)
CART: 0.961939 (0.005177)
NB: 0.830273 (0.011363)
SVM: 0.915668 (0.006663)


In [41]:
#Will still go with KNN
#make predictions on validation dataset
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.964064914992
[[   1    3    0    1    0    0]
 [   0  121   10   13   15    0]
 [   0    6  122    0    2    0]
 [   0   10    5 1565    9    0]
 [   0    1    8    4  453    0]
 [   0    0    1    3    2  233]]
                        precision    recall  f1-score   support

                  bump       1.00      0.20      0.33         5
        crossing_speed       0.86      0.76      0.81       159
 low_speed,using_phone       0.84      0.94      0.88       130
                  road       0.99      0.98      0.99      1589
               stopped       0.94      0.97      0.96       466
stopped, phone_at_rest       1.00      0.97      0.99       239

           avg / total       0.96      0.96      0.96      2588



In [42]:
#let us try cart now
#Will still go with KNN
#make predictions on validation dataset
cart = DecisionTreeClassifier()
cart.fit(X_train, Y_train)
predictions = knn.predict(X_validation)
print(accuracy_score(Y_validation, predictions))
print(confusion_matrix(Y_validation, predictions))
print(classification_report(Y_validation, predictions))

0.964064914992
[[   1    3    0    1    0    0]
 [   0  121   10   13   15    0]
 [   0    6  122    0    2    0]
 [   0   10    5 1565    9    0]
 [   0    1    8    4  453    0]
 [   0    0    1    3    2  233]]
                        precision    recall  f1-score   support

                  bump       1.00      0.20      0.33         5
        crossing_speed       0.86      0.76      0.81       159
 low_speed,using_phone       0.84      0.94      0.88       130
                  road       0.99      0.98      0.99      1589
               stopped       0.94      0.97      0.96       466
stopped, phone_at_rest       1.00      0.97      0.99       239

           avg / total       0.96      0.96      0.96      2588



In [43]:
#produces the same reults. 
#Let us try now file 22 which contains an accident and does not belong
#to the train set
#let us see if we detect an accident in file 22
#end the training with file 21. Walking to the airport
file=22
#This will create a new dataframe gps with all speeds and maxmin values and new vbles
data=pd.read_csv('/Users/empathybroker/Downloads/Data Science Challenge/all journeys/'
                +str(file)+'.csv')
xmax=[]
xmin=[]
ymax=[]
ymin=[]
zmax=[]
zmin=[]
gps=data[data['type']=='gps']
for i in range(len(gps)-1):
    a=gps.index[i]+1
    b=gps.index[i+1]
    x=data['x'].iloc[a:b].values  
    try:
        xmax.append(max(x))
    except:
        xmax.append(xmax[i-1])
    try:
        xmin.append(min(x))
    except:
        xmin.append(xmin[i-1])
    y=data['y'].iloc[a:b].values  
    try:
        ymax.append(max(y))
    except:
        ymax.append(ymax[i-1])
    try:
        ymin.append(min(y))
    except:
        ymin.append(ymin[i-1])
    z=data['z'].iloc[a:b].values  
    try:
        zmax.append(max(z))
    except:
        zmax.append(zmax[i-1])
    try:
        zmin.append(min(z))
    except:
        zmin.append(zmin[i-1])
#this will not work if first max value is empty
xmax=np.asarray(xmax)
ymax=np.asarray(ymax)
zmax=np.asarray(zmax)
xmin=np.asarray(xmin)
ymin=np.asarray(ymin)
zmin=np.asarray(zmin)
xdiff=xmax-xmin
ydiff=ymax-ymin
zdiff=zmax-zmin
#get new variables to check time lapse is about correct, and find difference in speed as new var
gps['timelapse']=gps['timestamp'].shift(-1)-gps['timestamp']
gps['speeddiff']=gps['speed'].shift(-1)-gps['speed']
gps=gps[:-1] #as I dont want the last line due to increases and shift
#New columns are added to be part of training process
gps['xmax']=xmax
gps['xmin']=xmin
gps['xdiff']=xdiff
gps['ymax']=ymax
gps['ymin']=ymin
gps['ydiff']=ydiff
gps['zmax']=zmax
gps['zmin']=zmin
gps['zdiff']=zdiff
#cleaning
del xmax,xmin,xdiff,ymax,ymin,ydiff,zmax,zmin,zdiff
#dropping unwanted columns
gps.drop(['type','lat','lon','height','accuracy','bearing','x','y','z'],axis=1,inplace=True)
#Creating a date from the timestamp
gps['timestamp']=gps['timestamp'].values.astype('datetime64[ms]')
gps['file']=str(file)
cols=['file','timestamp',
 'speed',
 'timelapse',
 'speeddiff',
 'xmax',
 'xmin',
 'xdiff',
 'ymax',
 'ymin',
 'ydiff',
 'zmax',
 'zmin',
 'zdiff']
gps=gps[cols]

/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:58: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Users/empathybroker/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:59: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [44]:
gps.drop('timelapse',axis=1,inplace=True)

In [46]:
array = gps.values
X_validation = array[:,2:13]
predictionsknn = knn.predict(X_validation)
predictionscart = cart.predict(X_validation)

In [48]:
gps['knn_pred']=predictionsknn
gps['cart_pred']=predictionscart

In [49]:
#let us now see if it has predicted any accident
gps.groupby(['knn_pred']).count()

file  timestamp  speed  speeddiff  xmax  xmin  xdiff  \
knn_pred                                                                      
crossing_speed           15         15     15         15    15    15     15   
low_speed,using_phone     4          4      4          4     4     4      4   
road                    390        390    390        390   390   390    390   
stopped                 428        428    428        428   428   428    428   

                       ymax  ymin  ydiff  zmax  zmin  zdiff  cart_pred  
knn_pred                                                                
crossing_speed           15    15     15    15    15     15         15  
low_speed,using_phone     4     4      4     4     4      4          4  
road                    390   390    390   390   390    390        390  
stopped                 428   428    428   428   428    428        428

In [50]:
gps.groupby(['cart_pred']).count()

file  timestamp  speed  speeddiff  xmax  xmin  xdiff  \
cart_pred                                                                      
accident                   1          1      1          1     1     1      1   
crossing_speed            12         12     12         12    12    12     12   
low_speed,using_phone      2          2      2          2     2     2      2   
road                     386        386    386        386   386   386    386   
stopped                  269        269    269        269   269   269    269   
stopped, phone_at_rest   167        167    167        167   167   167    167   

                        ymax  ymin  ydiff  zmax  zmin  zdiff  knn_pred  
cart_pred                                                               
accident                   1     1      1     1     1      1         1  
crossing_speed            12    12     12    12    12     12        12  
low_speed,using_phone      2     2      2     2     2      2         2  
road                     386   386    386   386   386    386       386  
stopped                  269   269    269   269   269    269       269  
stopped, phone_at_rest   167   167    167   167   167    167       167

In [52]:
#Cart predicts an accident at:
gps.loc[gps['cart_pred']=='accident']

file               timestamp  speed  speeddiff      xmax      xmin  \
6493   22 2015-04-24 19:28:41.024  11.94      -0.57  2.690964 -3.846207   

        xdiff      ymax      ymin      ydiff      zmax      zmin     zdiff  \
6493  6.53717  7.339661 -4.913544  12.253204  7.969635 -1.112747  9.082382   

                   knn_pred cart_pred  
6493  low_speed,using_phone  accident

In [53]:
gps.loc[gps['zmax']>5]

file               timestamp  speed  speeddiff      xmax      xmin  \
6493   22 2015-04-24 19:28:41.024  11.94      -0.57  2.690964 -3.846207   

        xdiff      ymax      ymin      ydiff      zmax      zmin     zdiff  \
6493  6.53717  7.339661 -4.913544  12.253204  7.969635 -1.112747  9.082382   

                   knn_pred cart_pred  
6493  low_speed,using_phone  accident

In [ ]:
#which is exactly where the accident occurred 